server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart-course?useSSL=false&serverTimezone=UTC
    username: root
    password: Csy10170655
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: course-service # 服务名称
  cloud:
    nacos:
      server-addr: 192.168.184.131:8848 # nacos地址
mybatis:
  mapper-locations: classpath:mapper/*.xml  #指定mapper xml文件位置
  configuration:
    map-underscore-to-camel-case: true  #mybatis开启驼峰映射

