server:
  port: 8080
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: 192.168.184.131:8848
    gateway:
      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/** # 这里是以请求路径作为判断规则
        - id: course
          uri: lb://course-service
          predicates:
            - Path=/course/**
#        - id: user
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**,/addresses/**
#        - id: trade
#          uri: lb://trade-service
#          predicates:
#            - Path=/orders/**
#        - id: pay
#          uri: lb://pay-service
#          predicates:
#            - Path=/pay-orders/**
sc:
  auth:
    excludePaths:  #无需校验的路径
      - /user/login
      - /user/register
      - /hi
